# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.21.1
_src_path: gh:oca/oca-addons-repo-template
ci: Travis
convert_readme_fragments_to_markdown: false
dependency_installation_mode: PIP
generate_requirements_txt: true
github_enable_stale_action: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'TODO: add repo description.'
repo_name: account-budgeting
repo_slug: account-budgeting
repo_website: https://github.com/OCA/account-budgeting
travis_apt_packages: []
travis_apt_sources: []
use_pyproject_toml: false
use_ruff: false

