# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.17.2
_src_path: gh:oca/oca-addons-repo-template
ci: Travis
dependency_installation_mode: PIP
generate_requirements_txt: true
github_enable_stale_action: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: You'll find modules that manage budgeting.
repo_name: Odoo Budgeting
repo_slug: account-budgeting
repo_website: https://github.com/OCA/account-budgeting
travis_apt_packages: []
travis_apt_sources: []

