# Copyright 2020 Ecosoft Co., Ltd. (http://ecosoft.co.th)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Budget Control",
    "version": "14.0.1.0.0",
    "category": "Accounting",
    "license": "AGPL-3",
    "author": "Ecosoft, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/account-budgeting",
    "depends": [
        "account",
        "mis_builder_budget",
        "web_widget_x2many_2d_matrix",
    ],
    "data": [
        "data/budget_transfer_sequence.xml",
        "security/budget_control_security_groups.xml",
        "security/budget_control_rules.xml",
        "security/ir.model.access.csv",
        "wizards/generate_budget_control_view.xml",
        "wizards/analytic_budget_info_view.xml",
        "wizards/confirm_state_budget_view.xml",
        "wizards/budget_commit_forward_info_view.xml",
        "wizards/budget_balance_forward_info_view.xml",
        "views/budget_menuitem.xml",
        "views/res_config_settings_views.xml",
        "views/budget_period_view.xml",
        "views/mis_report_kpi.xml",
        "views/mis_budget_item.xml",
        "views/budget_control_view.xml",
        "views/analytic_account_views.xml",
        "views/account_move_views.xml",
        "views/account_journal_view.xml",
        "views/budget_balance_forward_view.xml",
        "views/budget_commit_forward_view.xml",
        "views/budget_transfer_view.xml",
        "views/budget_transfer_item_view.xml",
        "report/budget_monitor_report_view.xml",
    ],
    "qweb": [
        "static/src/xml/budget_popover.xml",
    ],
    "demo": [
        "demo/budget_kpi.xml",
    ],
    "installable": True,
    "maintainers": ["kittiu"],
    "post_init_hook": "update_data_hooks",
    "uninstall_hook": "uninstall_hook",
    "development_status": "Alpha",
}
